[package]
name = "d19"
version = "0.1.0"
authors = ["Danny Hua <danny.hua@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
